import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

export default {
  default: [
    {
      type: 'category',
      label: 'Get started',
      collapsed: false,
      items: [
        'welcome',
        'why',
        'get-started/quickstart-register',
        'get-started/quickstart-build',
      ],
    },
    {
      type: 'category',
      label: 'Teams Platform',
      collapsed: false,
      link: {type: 'doc', id: 'teams/README'},
      items: [
        'teams/core-concepts',
        'teams/azure-configuration',
        {
          type: 'category',
          label: 'App Authentication Configuration',
          collapsed: true,
          link: {type: 'doc', id: 'teams/app-authentication/README'},
          items: [
            'teams/app-authentication/client-secret',
            'teams/app-authentication/federated-identity-credentials',
            'teams/app-authentication/user-managed-identity',
            'teams/app-authentication/troubleshooting',
          ],
        },
        {
          type: 'category',
          label: 'User Authentication Configuration',
          collapsed: true,
          link: {type: 'doc', id: 'teams/user-authentication/README'},
          items: [
            'teams/user-authentication/sso-setup',
            'teams/user-authentication/troubleshooting-sso',
          ],
        },
        'teams/manifest',
        'teams/enabling-in-copilot',
      ],
    },
    {
      type: 'category',
      label: 'TypeScript Guide',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'typescript'}],
    },
    {
      type: 'category',
      label: 'C# Guide',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'csharp'}],
    },
    {
      type: 'category',
      label: 'Python Guide',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'python'}],
    },
    {
      type: 'category',
      label: 'Developer Tools',
      collapsed: true,
      link: {type: 'doc', id: 'developer-tools/README'},
      items: [
        'developer-tools/cli',
        {
          type: 'category',
          label: '🛠️ DevTools',
          collapsed: true,
          link: {type: 'doc', id: 'developer-tools/devtools/README'},
          items: [
            'developer-tools/devtools/chat',
            'developer-tools/devtools/inspect',
            'developer-tools/devtools/cards',
          ],
        },
      ],
    },
    'privacy',
  ],
} satisfies SidebarsConfig;
