"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = {
    default: [{ type: 'autogenerated', dirName: '.' }],
    typescript: [{ type: 'autogenerated', dirName: '.' }],
    csharp: [{ type: 'autogenerated', dirName: '.' }],
    python: [{ type: 'autogenerated', dirName: '.' }]
};
