/**
 * Generates command reference markdown files from Commander command definitions.
 *
 * - Walks the Commander command tree
 * - For each leaf command, generates markdown with usage, options, and arguments
 * - Uses AUTOGENERATED markers — content between markers is overwritten, everything else is preserved
 * - Creates new files with an empty "Details" placeholder if they don't exist
 */

import { Command } from 'commander';
import fs from 'node:fs';
import path from 'node:path';

// Import all command objects directly (avoids triggering program.parse())
import { loginCommand, logoutCommand } from '../src/commands/auth/index.js';
import { statusCommand } from '../src/commands/status.js';
import { appCommand } from '../src/commands/app/index.js';
import { selfUpdateCommand } from '../src/commands/self-update.js';
import { configCommand } from '../src/commands/config/index.js';
import { projectCommand } from '../src/commands/project/index.js';

const DOCS_DIR = path.resolve(import.meta.dirname, '../../../teams.md/docs/cli/commands');
const START_MARKER = '<!-- AUTOGENERATED:START - Do not edit between these markers -->';
const END_MARKER = '<!-- AUTOGENERATED:END -->';

/** Escape angle brackets in description text so VitePress doesn't treat them as HTML tags. */
function escapeHtml(text: string): string {
  return text.replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

// Build root program (without parse)
const program = new Command();
program.name('teams').description('CLI for scaffolding Teams applications');
program.addCommand(loginCommand);
program.addCommand(logoutCommand);
program.addCommand(statusCommand);
program.addCommand(appCommand);
program.addCommand(selfUpdateCommand);
program.addCommand(configCommand);
program.addCommand(projectCommand);

interface CommandInfo {
  fullName: string; // e.g. "teams app create"
  filePath: string; // e.g. "app/create"
  description: string;
  usage: string;
  arguments: { name: string; description: string; required: boolean; defaultValue?: string }[];
  options: { flags: string; description: string; defaultValue?: string }[];
}

function getFilePath(parts: string[]): string {
  // Map command paths to file paths matching the plan's structure
  // e.g. ["app", "manifest", "download"] -> "app/manifest-download"
  // e.g. ["app", "auth", "sso", "setup"] -> "app/auth-sso-setup"
  // e.g. ["login"] -> "login"
  if (parts.length <= 1) {
    return parts[0] || 'index';
  }
  // First part is directory, rest joined with hyphens
  const dir = parts[0];
  const rest = parts.slice(1).join('-');
  return `${dir}/${rest}`;
}

function walkCommands(cmd: Command, parentParts: string[] = []): CommandInfo[] {
  const results: CommandInfo[] = [];
  const subcommands = cmd.commands;

  for (const sub of subcommands) {
    const name = sub.name();
    const currentParts = [...parentParts, name];
    const children = sub.commands;

    // Skip 'apps' — it's an alias for 'app list'
    if (name === 'apps' && parentParts.length === 0) continue;

    if (children.length > 0) {
      // Has subcommands — generate a page for this grouping command if it has its own action
      // Also recurse into children
      const hasAction = (sub as any)._actionHandler != null;
      if (hasAction || parentParts.length > 0) {
        // Generate a page for the grouping command itself (e.g. "app" interactive menu)
        results.push(extractCommandInfo(sub, currentParts));
      }
      results.push(...walkCommands(sub, currentParts));
    } else {
      // Leaf command
      results.push(extractCommandInfo(sub, currentParts));
    }
  }

  return results;
}

function extractCommandInfo(cmd: Command, parts: string[]): CommandInfo {
  const fullName = `teams ${parts.join(' ')}`;
  const filePath = getFilePath(parts);

  const args = cmd.registeredArguments.map((arg) => ({
    name: arg.name(),
    description: arg.description,
    required: arg.required,
    defaultValue: arg.defaultValue != null ? String(arg.defaultValue) : undefined,
  }));

  const options = cmd.options
    .filter((opt) => !['--help', '-h', '--version', '-V'].includes(opt.long || ''))
    .map((opt) => ({
      flags: opt.flags,
      description: opt.description || '',
      defaultValue: opt.defaultValue != null ? String(opt.defaultValue) : undefined,
    }));

  // Build usage string
  let usage = fullName;
  for (const arg of cmd.registeredArguments) {
    usage += arg.required ? ` <${arg.name()}>` : ` [${arg.name()}]`;
  }
  if (options.length > 0) {
    usage += ' [options]';
  }

  return {
    fullName,
    filePath,
    description: cmd.description(),
    usage,
    arguments: args,
    options,
  };
}

function generateMarkdown(info: CommandInfo): string {
  const lines: string[] = [];

  lines.push(`# ${info.fullName}`);
  lines.push('');
  lines.push(info.description);
  lines.push('');
  lines.push('## Usage');
  lines.push('');
  lines.push('```');
  lines.push(info.usage);
  lines.push('```');

  if (info.arguments.length > 0) {
    lines.push('');
    lines.push('## Arguments');
    lines.push('');
    lines.push('| Argument | Description | Required |');
    lines.push('|----------|-------------|----------|');
    for (const arg of info.arguments) {
      const req = arg.required ? 'Yes' : 'No';
      const rawDesc = arg.defaultValue
        ? `${arg.description} (default: \`${arg.defaultValue}\`)`
        : arg.description;
      const desc = escapeHtml(rawDesc);
      lines.push(`| \`${arg.name}\` | ${desc} | ${req} |`);
    }
  }

  if (info.options.length > 0) {
    lines.push('');
    lines.push('## Options');
    lines.push('');
    lines.push('| Flag | Description |');
    lines.push('|------|-------------|');
    for (const opt of info.options) {
      const rawDesc = opt.defaultValue
        ? `${opt.description} (default: \`${opt.defaultValue}\`)`
        : opt.description;
      const desc = escapeHtml(rawDesc);
      lines.push(`| \`${opt.flags}\` | ${desc} |`);
    }
  }

  return lines.join('\n');
}

function writeCommandDoc(info: CommandInfo): void {
  // Determine the file path
  let targetPath: string;
  const hasSubcommands = info.filePath.includes('/') && !info.filePath.includes('-');
  // Check if this is a grouping command (e.g. "app" -> "app/index")
  const isGrouping = program.commands.some(
    (c) => c.name() === info.filePath && c.commands.length > 0
  );

  if (isGrouping || info.filePath === 'app') {
    targetPath = path.join(DOCS_DIR, info.filePath, 'index.md');
  } else {
    targetPath = path.join(DOCS_DIR, `${info.filePath}.md`);
  }

  const autoContent = generateMarkdown(info);
  const frontmatter = [
    '---',
    `title: "${info.fullName.replace('teams ', '')}"`,
    `command: "${info.fullName}"`,
    '---',
  ].join('\n');

  // Check if file already exists
  if (fs.existsSync(targetPath)) {
    const existing = fs.readFileSync(targetPath, 'utf-8');
    const startIdx = existing.indexOf(START_MARKER);
    const endIdx = existing.indexOf(END_MARKER);

    if (startIdx !== -1 && endIdx !== -1) {
      // Replace content between markers
      const before = existing.slice(0, startIdx);
      const after = existing.slice(endIdx + END_MARKER.length);
      const newContent = `${before}${START_MARKER}\n${autoContent}\n${END_MARKER}${after}`;
      fs.writeFileSync(targetPath, newContent);
      console.log(`  Updated: ${path.relative(process.cwd(), targetPath)}`);
      return;
    }
  }

  // Create new file
  const dir = path.dirname(targetPath);
  fs.mkdirSync(dir, { recursive: true });

  const content = `${frontmatter}

${START_MARKER}
${autoContent}
${END_MARKER}
`;

  fs.writeFileSync(targetPath, content);
  console.log(`  Created: ${path.relative(process.cwd(), targetPath)}`);
}

// Main
console.log('Generating command reference docs...\n');

const commands = walkCommands(program);
console.log(`Found ${commands.length} commands:\n`);

for (const cmd of commands) {
  writeCommandDoc(cmd);
}

console.log(`\nDone! Generated ${commands.length} command reference files.`);
